// Mocks generated by Mockito 5.4.4 from annotations
// in flash_news/test/data/repositories/local_articles_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flash_news/domain/datasources/i_local_articles_datasource.dart'
    as _i2;
import 'package:flash_news/domain/entities/article.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ILocalArticlesDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalArticlesDatasource extends _i1.Mock
    implements _i2.ILocalArticlesDatasource {
  MockILocalArticlesDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> toggleFavorite(_i4.Article? article) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [article],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isArticleFavorite(String? articleId) => (super.noSuchMethod(
        Invocation.method(
          #isArticleFavorite,
          [articleId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.Article>> loadLocalArticles({
    int? limit = 10,
    dynamic offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadLocalArticles,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
      ) as _i3.Future<List<_i4.Article>>);
}
